Accept=Onartu
Close=Itxi
Price= Prezioa
SelectOption=Aukeratu

MainGUI.CreateSale= Eskaintza sortu
MainGUI.QuerySales= Eskaintzak konstsultatu
MainGUI.SelectOption=Aukeratu
MainGUI.MainTitle=Merkatua
MainGUI.Registrarse= Erregistratu
MainGUI.HacerLogin= Saioa Hasi
MainGUI.AceptarOferta= Eskaintza Onartu
MainGUI.VerOfertasAceptadas= Ikusi Onartutako Eskaintzak
MainGUI.ReportarUsuario= Saltzaile/Erosle Salatu
MainGUI.ComprasRealizadas= Compras Realizadas (en euskera)
MainGUI.GestionarReportes= Txostenak kudeatzea
MainGUI.GestionarComentarios= Iruzkinak kudeatzea
MainGUI.GestionarOfertas= Eskaintzak kudeatzea
MainGUI.MostrarSaldo= Balantze: 

MainGUI.GestionarSaldo= Balantzea Kudeatu

AceptarOfertaGUI.VerCarrito= Erakuts Kart

CreateSaleGUI.Title=Tituloa
CreateSaleGUI.Description=Deskripzioa
CreateSaleGUI.Status=Egoera
CreateSaleGUI.Category=Kategoria
CreateSaleGUI.Price=Prezioa
CreateSaleGUI.PriceMustBeGreaterThan0=Errorea, prezioa 0 baino handiagoa da
CreateSaleGUI.ProductCreated=Eskaintza sortuta
CreateSaleGUI.CreateProduct=Sortu Eskaintza
CreateSaleGUI.ErrorNumber=Errorea, prezioa zenbaki bat izan behar da
CreateSaleGUI.ErrorQuery=Errorea, datuak falta dira
CreateSaleGUI.LoadPicture=Argazkia igo
CreateSaleGUI.PublicationDate=Argitarapen eguna
CreateSaleGUI.CantidadProductos=Kantitatea

Registrarse.Correo=Posta Elektronikoa
Registrarse.Nombre=Izena
Registrarse.Contrasena=Pasahitza
Registrarse.Registrarse=Erregistratu
Registrarse.Vendedor=Saltzailea
Registrarse.Comprador=Eroslea
Registrarse.ErrorGmail=Errorea, mezu elektronikoak @gmail.com eduki behar du amaieran
Registrarse.ErrorTipo=Errorea, ez da kontu motarik hautatu
Registrarse.ErrorDuplicado=Errorea, erabiltzaile hori dagoeneko existitzen da
Registrarse.ErrorVacio=Errorea, eremu bat hutsik dago
Registrarse.Exito=Behar bezala erregistratu da

Registrarse.Saldo=Balantze
Registrarse.ErrorSaldoNoNumerico=Errorea, balantze es numerikoa
Registrarse.ErrorSaldoNegativo=Errorea, balantze negatiboa
Registrarse.ErrorBaneado= Errorea, erabiltzailea salatuta dago sistematik
Registrarse.ErrorMaestro= Errorea, pasahitz nagusia okerra da
Registrarse.ContrasenaMaestra=Pasahitz Nagusia
Registrarse.Administrador=Nagusi

HacerLogin.Correo=Posta Elektronikoa
HacerLogin.HacerLogin=Saioa Hasi
HacerLogin.ErrorGmail=Errorea, erabiltzaile hori ez da existitzen
HacerLogin.ErrorContrase√±a=Errorea, pasahitza okerra da
HacerLogin.ErrorVacio=Errorea, eremu bat hutsik dago
HacerLogin.Exito=Saioa arrakastaz hasi da, ongi etorri!

ContraOferta.PrecioOriginal=Jatorrizko Prezioa
ContraOferta.PrecioOfrecido=Eskainitako Prezioa
ContraOferta.Compra=Hautatutako Eskaintza
ContraOferta.Confirmar=Baieztu
ContraOferta.ErrorVacio=Errorea, 0 baino handiagoa den zenbateko bat eskaini behar duzu
ContraOferta.ErrorSobrePrecio=Errorea, ezin duzu produktuaren prezioa baino gehiago eskaini
ContraOferta.Exito=Arrakastaz onartu da
ContraOferta.AÒadirAlCarrito= Karritora gaindu

AceptarContraOfertaGUI.Confirmacion= Kontraeskaintza onartu nahi al duzu?

VerOfertasAceptadasGUI.Titulo=Izenburua
VerOfertasAceptadasGUI.PrecioOriginal=Jatorrizko Prezioa
VerOfertasAceptadasGUI.Contraoferta=Kontraeskaintza
VerOfertasAceptadasGUI.Comprador=Eroslea
VerOfertasAceptadasGUI.SinContraofertas=Ez dago kontraeskaintzarik
VerOfertasAceptadasGUI.Contraofertas=Kontraeskaintzak
VerOfertasAceptadasGUI.BuscarProductos=Eskaintzak Bilatu

ReportarUsuarioGUI.Titulo=Saltzaile/Erosle salatu
ReportarUsuarioGUI.CorreoReportado= E-posta salatzeko
ReportarUsuarioGUI.RazonReporte= Salaketaren arrazoia
ReportarUsuarioGUI.RealizarReporte= Salatu
ReportarUsuarioGUI.Exito= Behar bezala salatuta

VerReporteGUI.Reportante= Salatzailea
VerReporteGUI.Reportado= Salatuta
VerReporteGUI.Banear= Baneatu
VerReporteGUI.BorrarReporte= Salatea borratu
VerReporteGUI.ExitoUsuarioBaneado= Ondo baneatuta salatutako erabiltzailea, ateratzen..
VerReporteGUI.ExitoBorrado= Ondo ezabatuta salatea, ateratzen..

ComentarGUI.Titulo= Iruzkin
ComentarGUI.Asunto= Gai
ComentarGUI.Puntuacion= Puntuazioa
ComentarGUI.Comentario= Iruzkin
ComentarGUI.RealizarComentario= Iruzkin
ComentarGUI.Exito= Behar bezala iruzkinduta
ComentarGUI.ErrorNumerico= Errorea, ratinga 0tik 10era zenbaki bat izan behar da

VerComentarioGUI.Comentador= Iruzkitzailea
VerComentarioGUI.Comentado= Iruzkinduta
VerComentarioGUI.MostrarPuntuacion= Puntuazioa
VerComentarioGUI.BorrarComentario= Iruzkina ezabatu
VerComentarioGUI.ExitoBorrado= Iruzkina ezabatuta, ateratzen..

VerCarritoGUI.VerCarrito= Erakuts Kart
VerCarritoGUI.Productos= Karteko produktuak (doble klika ezabatzeko)
VerCarritoGUI.AceptarCarrito= Konfirmatu kompra

QuerySalesGUI.Search=Bilatu
QuerySalesGUI.Close= Itxi
QuerySalesGUI.Nombre= Izena
QuerySalesGUI.PrecioMaximo= Prezioa Maximoa
QuerySalesGUI.Fecha= Data
QuerySalesGUI.NoProducts=Ez daude eskaintzak
QuerySalesGUI.Price=Prezioa
QuerySalesGUI.FindProducts=Eskaintzak bilatu
QuerySalesGUI.Products=Eskaintzak (Double-click eskaintza ikusteko)

ShowSaleGUI.Title=Eskaintza xehestasunak
ShowSaleGUI.Comentarios=Iruzkinak ikusi
ShowSaleGUI.Vendedor=Saltzailea ikusi
ShowSaleGUI.btnInfoVendedor= Saltzailea erakutsi

MostrarComentariosGUI.Titulo= Iruzkinak
MostrarComentariosGUI.Asunto= Gai
MostrarComentariosGUI.Rating= Puntuazioa
MostrarComentariosGUI.Fecha= Data
MostrarComentariosGUI.Comentarios= Iruzkinak
MostrarComentariosGUI.Buscar= Bilatu

GestionarComentariosGUI.Asunto= Gaia
GestionarComentariosGUI.Puntuacion= Puntu
GestionarComentariosGUI.Fecha= Data
GestionarComentariosGUI.Comentado= Iruzkindu erabiltzailea
GestionarComentariosGUI.Comentador= Iruzkinduta
GestionarComentariosGUI.Buscar= Bilatu
GestionarComentariosGUI.SinComentarios= Ez daude iruzkindik

GestionarReportesGUI.Fecha= Data
GestionarReportesGUI.Reportado= Erabiltzaile salatua
GestionarReportesGUI.SinReportes= Ez daude salaturik erregistratuak

BorrarOfertaGUI.Borrar= Ezabatu
BorrarOfertaGUI.Descatalogar= Deskatalogatu
BorrarOfertaGUI.ExitoBorrado=  Ondo ezabatu da salketa, ateratzen..
BorrarOfertaGUI.ExitoDescatalogado= Ondo deskatalogatu da salketa, ateratzen..

GestionarSaldoGUI.AnadirSaldo = Balantzea Geitu
GestionarSaldoGUI.RetirarSaldo = Balantzea Kendu
GestionarSaldoGUI.CantSaldo = Kentzeko/geitzeko balantzea:
GestionarSaldoGUI.ErrorSaldoInsuficiente = Errorea, balantzea ez daukazu

DataAccess.SaleAlreadyExist=ERROR, Eskaintza existizen da
DataAccess.ErrorSaleMustBeLaterThanToday=ERROR, data gaur baino beranduago izan behar da
DataAccess.ErrorFileNotUploadedException=ERROR, Argazkia igo behar da